import { BaseService } from '@/core/BaseService';
import { PrismaClient } from '@/generated/prisma/client';
import { PaginationResult } from '@/types/types';
import { CreateProductInput, UpdateProductInput } from './product.validation';
import { v4 as uuidv4 } from 'uuid'; // Ensure you have 'uuid' installed or use a simple random string

// ⚠️ Interface for the Mock Data (Replace with Prisma Model type later)
interface ProductModel {
    id: string;
    name: string;
    description?: string | null;
    status: string;
    createdAt: Date;
    updatedAt: Date;
}

export class ProductService extends BaseService<any> {
    // In-memory storage for Demo purposes
    private demoStorage: ProductModel[] = [
        {
            id: '550e8400-e29b-41d4-a716-446655440000',
            name: 'Demo Product 1',
            description: 'This is a demo item generated by the service',
            status: 'active',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            id: '550e8400-e29b-41d4-a716-446655440001',
            name: 'Demo Product 2',
            description: 'Another demo item',
            status: 'inactive',
            createdAt: new Date(),
            updatedAt: new Date(),
        },
    ];

    constructor(prisma: PrismaClient) {
        super(prisma, 'Product', {
            enableSoftDelete: true,
            enableAuditFields: true,
        });
    }

    protected getModel() {
        return this.prisma.product;
    }

    /**
     * Create Product
     * Current: Returns Demo Data
     * TODO: Uncomment super.create() to use Database
     */
    public async create(data: CreateProductInput, include?: any): Promise<any> {
        // --- REAL DB IMPLEMENTATION ---
        // return super.create(data, include);

        // --- DEMO IMPLEMENTATION ---
        const newItem: ProductModel = {
            id: uuidv4(),
            name: data.name,
            description: data.description || null,
            status: data.status || 'active',
            createdAt: new Date(),
            updatedAt: new Date(),
        };
        this.demoStorage.push(newItem);
        return newItem;
    }

    /**
     * Find All Products
     * Current: Returns Demo Data
     * TODO: Uncomment super.findMany() to use Database
     */
    public async findMany(
        filters: any = {},
        pagination: any = { page: 1, limit: 10 },
        orderBy?: any,
        include?: any
    ): Promise<PaginationResult<any>> {
        // --- REAL DB IMPLEMENTATION ---
        // return super.findMany(filters, pagination, orderBy, include);

        // --- DEMO IMPLEMENTATION ---
        const page = pagination.page || 1;
        const limit = pagination.limit || 10;
        const total = this.demoStorage.length;
        const totalPages = Math.ceil(total / limit);

        return {
            data: this.demoStorage,
            total: total,
            page: page,
            limit: limit,
            totalPages: totalPages,
            hasNext: page < totalPages,
            hasPrevious: page > 1,
        };
    }

    /**
     * Find One Product by ID
     * Current: Returns Demo Data
     * TODO: Uncomment super.findById() to use Database
     */
    public async findById(id: string, include?: any): Promise<any | null> {
        // --- REAL DB IMPLEMENTATION ---
        // return super.findById(id, include);

        // --- DEMO IMPLEMENTATION ---
        return this.demoStorage.find(item => item.id === id) || null;
    }

    /**
     * Update Product
     * Current: Returns Demo Data
     * TODO: Uncomment super.updateById() to use Database
     */
    public async updateById(id: string, data: UpdateProductInput, include?: any): Promise<any> {
        // --- REAL DB IMPLEMENTATION ---
        // return super.updateById(id, data, include);

        // --- DEMO IMPLEMENTATION ---
        const index = this.demoStorage.findIndex(item => item.id === id);
        if (index === -1) throw new Error('Product not found');

        this.demoStorage[index] = { ...this.demoStorage[index], ...data, updatedAt: new Date() };
        return this.demoStorage[index];
    }

    /**
     * Delete Product
     * Current: Returns Demo Data
     * TODO: Uncomment super.deleteById() to use Database
     */
    public async deleteById(id: string): Promise<any> {
        // --- REAL DB IMPLEMENTATION ---
        // return super.deleteById(id);

        // --- DEMO IMPLEMENTATION ---
        const index = this.demoStorage.findIndex(item => item.id === id);
        if (index === -1) throw new Error('Product not found');

        const deleted = this.demoStorage[index];
        this.demoStorage = this.demoStorage.filter(item => item.id !== id);
        return deleted;
    }

    /**
     * Check if exists
     */
    public async exists(filters: any): Promise<boolean> {
        // --- REAL DB IMPLEMENTATION ---
        // return super.exists(filters);

        // --- DEMO IMPLEMENTATION ---
        if (filters.id) {
            return !!this.demoStorage.find(item => item.id === filters.id);
        }
        return false;
    }
}
