// scripts/generate-module-with-demo.ts
import fs from 'fs';
import path from 'path';

// 1. Get Module Name from CLI
const moduleName = process.argv[2];

if (!moduleName) {
    console.error('❌ Please provide a module name (e.g., Product)');
    console.error('👉 Usage: npx ts-node scripts/generate-module-with-demo.ts Product');
    process.exit(1);
}

// 2. Helpers for casing
const capitalize = (s: string) => s.charAt(0).toUpperCase() + s.slice(1);
const uncapitalize = (s: string) => s.charAt(0).toLowerCase() + s.slice(1);

const PascalName = capitalize(moduleName); // e.g., Product
const camelName = uncapitalize(moduleName); // e.g., product

const baseDir = path.join(process.cwd(), 'src', 'modules', PascalName);

// 3. Ensure directory exists
if (!fs.existsSync(baseDir)) {
    fs.mkdirSync(baseDir, { recursive: true });
}

// --- TEMPLATES ---

// 1. Validation Template
const validationTemplate = `import { z } from 'zod';

export const ${PascalName}Validation = {
    // Create ${PascalName}
    create: z.object({
        name: z.string().min(2, 'Name must be at least 2 characters').max(100),
        description: z.string().max(500).optional(),
        status: z.enum(['active', 'inactive']).optional().default('active'),
    }).strict(),

    // Update ${PascalName}
    update: z.object({
        name: z.string().min(2).max(100).optional(),
        description: z.string().max(500).optional(),
        status: z.enum(['active', 'inactive']).optional(),
    }).strict(),

    // Params validation
    params: {
        id: z.object({
            id: z.string().uuid('Invalid ID format'),
        }),
    }
};

export type Create${PascalName}Input = z.infer<typeof ${PascalName}Validation.create>;
export type Update${PascalName}Input = z.infer<typeof ${PascalName}Validation.update>;
`;

// 2. Service Template (WITH DEMO DATA)
const serviceTemplate = `import { BaseService } from '@/core/BaseService';
import { PrismaClient } from '@/generated/prisma/client';
import { PaginationResult } from '@/types/types';
import { Create${PascalName}Input, Update${PascalName}Input } from './${camelName}.validation';
import { v4 as uuidv4 } from 'uuid'; // Ensure you have 'uuid' installed or use a simple random string

// ⚠️ Interface for the Mock Data (Replace with Prisma Model type later)
interface ${PascalName}Model {
    id: string;
    name: string;
    description?: string | null;
    status: string;
    createdAt: Date;
    updatedAt: Date;
}

export class ${PascalName}Service extends BaseService<any> { 
    
    // In-memory storage for Demo purposes
    private demoStorage: ${PascalName}Model[] = [
        {
            id: '550e8400-e29b-41d4-a716-446655440000',
            name: 'Demo ${PascalName} 1',
            description: 'This is a demo item generated by the service',
            status: 'active',
            createdAt: new Date(),
            updatedAt: new Date()
        },
        {
            id: '550e8400-e29b-41d4-a716-446655440001',
            name: 'Demo ${PascalName} 2',
            description: 'Another demo item',
            status: 'inactive',
            createdAt: new Date(),
            updatedAt: new Date()
        }
    ];

    constructor(prisma: PrismaClient) {
        super(prisma, '${PascalName}', {
            enableSoftDelete: true,
            enableAuditFields: true
        });
    }

    protected getModel() {
        return this.prisma.${camelName}; 
    }

    /**
     * Create ${PascalName}
     * Current: Returns Demo Data
     * TODO: Uncomment super.create() to use Database
     */
    public async create(data: Create${PascalName}Input, include?: any): Promise<any> {
        // --- REAL DB IMPLEMENTATION ---
        // return super.create(data, include);

        // --- DEMO IMPLEMENTATION ---
        const newItem: ${PascalName}Model = {
            id: uuidv4(),
            name: data.name,
            description: data.description || null,
            status: data.status || 'active',
            createdAt: new Date(),
            updatedAt: new Date(),
        };
        this.demoStorage.push(newItem);
        return newItem;
    }

    /**
     * Find All ${PascalName}s
     * Current: Returns Demo Data
     * TODO: Uncomment super.findMany() to use Database
     */
    public async findMany(
        filters: any = {},
        pagination: any = { page: 1, limit: 10 },
        orderBy?: any,
        include?: any
    ): Promise<PaginationResult<any>> {
        // --- REAL DB IMPLEMENTATION ---
        // return super.findMany(filters, pagination, orderBy, include);

        // --- DEMO IMPLEMENTATION ---
        const page = pagination.page || 1;
        const limit = pagination.limit || 10;
        const total = this.demoStorage.length;
        const totalPages = Math.ceil(total / limit);

        return {
            data: this.demoStorage,
            total: total,
            page: page,
            limit: limit,
            totalPages: totalPages,
            hasNext: page < totalPages,
            hasPrevious: page > 1
        };
    }

    /**
     * Find One ${PascalName} by ID
     * Current: Returns Demo Data
     * TODO: Uncomment super.findById() to use Database
     */
    public async findById(id: string, include?: any): Promise<any | null> {
        // --- REAL DB IMPLEMENTATION ---
        // return super.findById(id, include);

        // --- DEMO IMPLEMENTATION ---
        return this.demoStorage.find(item => item.id === id) || null;
    }

    /**
     * Update ${PascalName}
     * Current: Returns Demo Data
     * TODO: Uncomment super.updateById() to use Database
     */
    public async updateById(id: string, data: Update${PascalName}Input, include?: any): Promise<any> {
        // --- REAL DB IMPLEMENTATION ---
        // return super.updateById(id, data, include);

        // --- DEMO IMPLEMENTATION ---
        const index = this.demoStorage.findIndex(item => item.id === id);
        if (index === -1) throw new Error('${PascalName} not found');

        this.demoStorage[index] = { ...this.demoStorage[index], ...data, updatedAt: new Date() };
        return this.demoStorage[index];
    }

    /**
     * Delete ${PascalName}
     * Current: Returns Demo Data
     * TODO: Uncomment super.deleteById() to use Database
     */
    public async deleteById(id: string): Promise<any> {
        // --- REAL DB IMPLEMENTATION ---
        // return super.deleteById(id);

        // --- DEMO IMPLEMENTATION ---
        const index = this.demoStorage.findIndex(item => item.id === id);
        if (index === -1) throw new Error('${PascalName} not found');

        const deleted = this.demoStorage[index];
        this.demoStorage = this.demoStorage.filter(item => item.id !== id);
        return deleted;
    }

    /**
     * Check if exists
     */
    public async exists(filters: any): Promise<boolean> {
        // --- REAL DB IMPLEMENTATION ---
        // return super.exists(filters);

        // --- DEMO IMPLEMENTATION ---
        if (filters.id) {
            return !!this.demoStorage.find(item => item.id === filters.id);
        }
        return false;
    }
}
`;

// 3. Controller Template
const controllerTemplate = `import { Request, Response } from 'express';
import { BaseController } from '@/core/BaseController';
import { ${PascalName}Service } from './${camelName}.service';
import { HTTPStatusCode } from '@/types/HTTPStatusCode';

export class ${PascalName}Controller extends BaseController {
    constructor(private service: ${PascalName}Service) {
        super();
    }

    /**
     * Create a new ${PascalName}
     */
    public create = async (req: Request, res: Response) => {
        const body = req.validatedBody;
        this.logAction('create', req, { body });
        
        const result = await this.service.create(body);
        
        return this.sendCreatedResponse(res, result, '${PascalName} created successfully (DEMO)');
    };

    /**
     * Get all ${PascalName}s
     */
    public getAll = async (req: Request, res: Response) => {
        const pagination = this.extractPaginationParams(req);
        this.logAction('getAll', req, { pagination });

        const result = await this.service.findMany({}, pagination);

        return this.sendPaginatedResponse(
            res, 
            {
                page: result.page,
                limit: result.limit,
                total: result.total,
                totalPages: result.totalPages,
                hasNext: result.hasNext,
                hasPrevious: result.hasPrevious
            }, 
            '${PascalName}s retrieved successfully', 
            result.data
        );
    };

    /**
     * Get single ${PascalName}
     */
    public getOne = async (req: Request, res: Response) => {
        const { id } = req.validatedParams;
        this.logAction('getOne', req, { id });

        const result = await this.service.findById(id);

        if (!result) {
            return this.sendResponse(res, '${PascalName} not found', HTTPStatusCode.NOT_FOUND);
        }

        return this.sendResponse(res, '${PascalName} retrieved successfully', HTTPStatusCode.OK, result);
    };

    /**
     * Update ${PascalName}
     */
    public update = async (req: Request, res: Response) => {
        const { id } = req.validatedParams;
        const body = req.validatedBody;
        this.logAction('update', req, { id, body });
        
        const exists = await this.service.exists({ id });
        if (!exists) {
            return this.sendResponse(res, '${PascalName} not found', HTTPStatusCode.NOT_FOUND);
        }

        const result = await this.service.updateById(id, body);
        
        return this.sendResponse(res, '${PascalName} updated successfully', HTTPStatusCode.OK, result);
    };

    /**
     * Delete ${PascalName}
     */
    public delete = async (req: Request, res: Response) => {
        const { id } = req.validatedParams;
        this.logAction('delete', req, { id });
        
        const exists = await this.service.exists({ id });
        if (!exists) {
            return this.sendResponse(res, '${PascalName} not found', HTTPStatusCode.NOT_FOUND);
        }

        await this.service.deleteById(id);
        
        return this.sendResponse(res, '${PascalName} deleted successfully', HTTPStatusCode.OK);
    };
}
`;

// 4. Routes Template
const routesTemplate = `import { Router, Request, Response } from 'express';
import { ${PascalName}Controller } from './${camelName}.controller';
import { ${PascalName}Validation } from './${camelName}.validation';
import { validateRequest } from '@/middleware/validation';
import { asyncHandler } from '@/middleware/asyncHandler';
import { authenticate } from '@/middleware/auth';

export class ${PascalName}Routes {
    private router: Router;
    private controller: ${PascalName}Controller;

    constructor(controller: ${PascalName}Controller) {
        this.router = Router();
        this.controller = controller;
        this.initializeRoutes();
    }

    private initializeRoutes(): void {
        const createValidator = validateRequest({ body: ${PascalName}Validation.create });
        const updateValidator = validateRequest({ 
            params: ${PascalName}Validation.params.id, 
            body: ${PascalName}Validation.update 
        });
        const idValidator = validateRequest({ params: ${PascalName}Validation.params.id });

        // Define Routes
        this.router.post('/', createValidator, asyncHandler((req, res) => this.controller.create(req, res)));
        this.router.get('/', asyncHandler((req, res) => this.controller.getAll(req, res)));
        this.router.get('/:id', idValidator, asyncHandler((req, res) => this.controller.getOne(req, res)));
        this.router.patch('/:id', updateValidator, asyncHandler((req, res) => this.controller.update(req, res)));
        this.router.delete('/:id', idValidator, asyncHandler((req, res) => this.controller.delete(req, res)));
    }

    public getRouter(): Router {
        return this.router;
    }
}
`;

// 5. Module Template
const moduleTemplate = `import { BaseModule } from '@/core/BaseModule';
import { ${PascalName}Service } from './${camelName}.service';
import { ${PascalName}Controller } from './${camelName}.controller';
import { ${PascalName}Routes } from './${camelName}.routes';

export class ${PascalName}Module extends BaseModule {
    public readonly name = '${PascalName}Module';
    public readonly version = '1.0.0';
    public readonly dependencies = ['AuthModule'];

    private service!: ${PascalName}Service;
    private controller!: ${PascalName}Controller;
    private routes!: ${PascalName}Routes;

    protected async setupServices(): Promise<void> {
        this.service = new ${PascalName}Service(this.context.prisma);
    }

    protected async setupRoutes(): Promise<void> {
        this.controller = new ${PascalName}Controller(this.service);
        this.routes = new ${PascalName}Routes(this.controller);

        this.router.use('/api/${camelName}s', this.routes.getRouter());
    }
}
`;

// --- WRITE FILES ---

const files = [
    { name: `${camelName}.validation.ts`, content: validationTemplate },
    { name: `${camelName}.service.ts`, content: serviceTemplate },
    { name: `${camelName}.controller.ts`, content: controllerTemplate },
    { name: `${camelName}.routes.ts`, content: routesTemplate },
    { name: `${PascalName}Module.ts`, content: moduleTemplate },
];

files.forEach(file => {
    const filePath = path.join(baseDir, file.name);
    fs.writeFileSync(filePath, file.content);
    console.log(`✅ Created ${file.name}`);
});

console.log(`
✨ Module ${PascalName} created successfully at src/modules/${PascalName}

👉 **Next Steps:**
1. Register the module in 'src/index.ts':
   import { ${PascalName}Module } from './modules/${PascalName}/${PascalName}Module';
   // ...
   app.registerModule(new ${PascalName}Module());

2. Start your server. You can now use the endpoints at /api/${camelName}s 
   (They will return DEMO data until you uncomment the DB calls in the service file).
`);
